### ISSUE TITLE
Idea: 1v1 mecha champion fight

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#105]
I think it would be nice to have a 1v1 fight between the player and a representative of whatever road rage faction they are fighting.  The champion would be piloting a special custom design, with equipment that would not be available by other means.

I'm thinking of adding a new role tag `Champion` which would not be selected otherwise, and would also not be sold in shops.

I'm uncertain how to set up the 1v1 fight.  It looks a lot like the `DDBAMO_PracticeDuel`, then select a mecha of  appropriate threat with the role `Champion`.  But I'm confused with the `plotultility` stuff, like constructing `CharacterMover` without saving or invoking the constructed object.

The mission would allow salvaging, so the player has a chance to acquire the special champion-only equipment.

**Comment by AmkG** [comment]
Alternately instead of having separate explicit designs that have a `role_list = (Champion,)`, we can have a `make_champion` function in a new `gears.champions` module, which modifies engines, armor, power sources, etc., appending "Champion" to the `desig` of modified gears.  So the 1v1 mecha champion fight would use the normal generate-one-mecha code, then pass it through `make_champion`.

We could make a `mav_championflag.png` which is just a flagpole with the faction colors in a flag, then generate the `get_sprite()` for champion mechas by rendering the champion flag, then the normal `imagename`.

**Comment by jwvhewitt** [comment]
A function to automatically upgrade mecha is what was used in GearHead2; there was a list of special upgrade weapons, most of which could only be obtained in this way.

**Comment by jwvhewitt** [comment]
Also in GH2, the upgrade bonus is applied to all enemy pilots that are permanent characters, not counting those who are just generated for a single fight. All the enemy factions in GHC have 3-4 characters generated in a secret (completely inaccessible) storage room that show up as commanders.

**Comment by AmkG** [comment]
Okay, seems good.  My intent is to do stuff like upgrade weapon reach, damage, accuracy, penetration stats, or add valid attributes, rather than a specialized list of upgrade targets.  Always increase engine size as well, possibly movesystem sizes, as well as armor size upgrades.  Gotta respect the slots limit of each mecha module.

**Comment by AmkG** [comment]
> All the enemy factions in GHC have 3-4 characters generated in a secret (completely inaccessible) storage room that show up as commanders.

How do I get at them?  I see some use of `seek_element` with a `_commander` argument, is that the way?

**Comment by jwvhewitt** [comment]
Yes, you seek_element and find a character that belongs to the faction. Or in the case of a 1 on 1 fight, you could just define the character in the plot that sets the fight and then you don't have to search for them.

One benefit of GH2's list of upgrade weapons is that it allowed different characters to have different themes, and equip them accordingly- Soldier, Pirate, Industrial, Dragon, etc.

I've been planning to add a mecha arena to one of the towns in the deadzone, which would work more like the GH2 arenas than the GH1 arenas: it would be a series of 1 on 1 battles against NPCs, and after defeating them most of the NPCs would become potential lancemates.

**Comment by AmkG** [comment]
> One benefit of GH2's list of upgrade weapons is that it allowed different characters to have different themes, and equip them accordingly- Soldier, Pirate, Industrial, Dragon, etc.

Hmm, interesting.  Perhaps one way would be to pass in the theme to the upgrader.  The theme would then specify what upgrades to add to items.

For example, a `DragonTheme` would add `BurnAttack` on any item that can take it.  A `RaiderTheme` would prefer to increase MoveSys sizes if available, possibly reducing armor in the same limb just to do that, or install movesystems if there are none.  `BomberTheme` would attempt to add `Blast1` to items.  Stuff like that.  `MilitaryTheme` would improve armor sizes (making them integral if the module it is on ha no free space and it is not currently integral) and upgrade to Advanced.

Items modified by a theme would have their designation modified by the theme name.  If the theme does not modify an item, the item is modified by a fallback `ChampionTheme` which just improves some stat somehow.

**Comment by AmkG** [comment]
Well champions now exist, and there's even a rare 1v1 fight against them, so I'll close this now.
