### ISSUE TITLE
AttributeError: 'Armor' object has no attribute 'gear_up'

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#11]
[fail.txt](https://github.com/jwvhewitt/gearhead-caramel/files/4491617/fail.txt)

**Comment by AmkG** [comment]
Uploading save file as well, as maybe it gives a hint: 
[save.zip](https://github.com/jwvhewitt/gearhead-caramel/files/4491637/save.zip)

**Comment by AmkG** [comment]
FWIW I removed an armor from my Trailblazer in order to free up space for my EW, which I moved from my torso to my head (removing the head armor for the space) in order to get a nifty new engine in the torso.

**Comment by AmkG** [comment]
Okay, looks like the armor is somehow in my party?  And because it has no `pilot` attribute, it skips this check:https://github.com/jwvhewitt/gearhead-caramel/blob/a68f89c920021ee25603f50525367517a63f3acd/gears/__init__.py#L403

And instead gets to this check: https://github.com/jwvhewitt/gearhead-caramel/blob/a68f89c920021ee25603f50525367517a63f3acd/gears/__init__.py#L407

And because the armor is still operational, it is added to the usable party.

**Comment by jwvhewitt** [comment]
Yes, that's exactly what happened. I think that when converting code from Pascal to Python, I must have assumed that is_operational only returns True for gears that are capable of taking actions. This bug has been fixed.

**Comment by AmkG** [comment]
Pushed yet? Cannot confirm yet...
