### ISSUE TITLE
Installing/Removing Cyberware on lancemates!

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#118]
The current system allows the player character to purchase, install, replace and remove cyberware from zir own body.

Should we allow the player to install cyberware in lancemates?  In previous games this was possible.

However, the ability to remove cyberware means that the player can be evil, coerce lancemates to remove their cyberware, kick them off the lance, and install the cyberware in zirself.

GHC has a (partially implemented) system where the lancemate labels all the equipment they brought to the lance, so that kicking them off the lance results in the lancemate coming and recovering their items.  But if you think of that in terms of cyberware where you take your lancemate's cyberware and install it into another character's body, I hope you imagine that this would be a bloody, [Repo Men](https://tvtropes.org/pmwiki/pmwiki.php/Film/RepoMen) mess when you kick them off the lance..

So here's a tentative plan for enabling lancemate cyberware manipulation.:

* Cyberware includes a definite `owner` field.  It could be `None` for shop-generated items.
* The `CyberwareInstaller` checks the `owner` of the `BaseCyberware`.  If it is not `None` then it should match the character being installed in.  Otherwise it fails with an alert: "You do not own this cyberware!"
* On installation, the `owner` is set to the character it was just installed in.
* The `cyberdoc.UI` displays the `owner` of the cyberware in the "AVAILABLE" list, instead of the "[Inv]" tag.

So even if you take out the cyberware from a lancemate you can't use it on your character, or another lancemate.  This also suggests that shops should force items with a non-`None` `owner` field to sell for 0 credits.

Thoughts?  Seems reasonable?

**Comment by AmkG** [comment]
Hmm so I tried the `owner` thing, but when the `owner` field is set while the cyberware is installed into the character the game cannot be loaded due to infinite loop.

Hmm.

Maybe I can set the `owner` of a cyberware when *removing* it from the character, check if it has an `owner` before installing (and reject the install if it is owned by somebody else), then clear `owner` prior to installing.  That would require that we disallow characters being edited in the Gear Editor though, i.e. #119.

**Comment by AmkG** [comment]
No that still won't work, because the `owner` can put the item into its inventory, leading back to the same circular recursion that would cause problems with `deepcopy`... hmm

**Comment by AmkG** [comment]
So here's an insane idea.

Let's model reality even more.

Every `Being` has a `dna_signature`, which is a random 32-digit hex string (128 bits of entropy) serving as a UUID.  For compatibility with older savefiles we could make it a `@property` that checks if `self` has a `_dna_signature` property and uses that, but if not will generate a random one, then add the `_dna_signature` generation to the `__init__` constructor as well.

The cyberware copies the `dna_signature` when it is installed/removed, because the reason that cyberware that was owned by one person cannot be installed in another person is because the genetic signature of the original owner is put in the cyberware organ, in order to prevent biological rejection.  Even when removed from the owner, the genetic markers are still present and impractical to remove (so that once the cyberware has been used, its sell value is 0 credits since it can no longer be reused by anyone anyway).

The cute thing is that if we ever have a plot where an evil clone of someone exists, we can have the evil clone and the good clone coexist at the same time, then later you can take the evil clone and remove its cyberware and install it in the good clone (or the evil clone can kidnap the good clone and steal their cyberware and install it to themselves) and that would still work, because to create a clone of someone you `copy.deepcopy` their gear, which copies the `_dna_signature` attribute as well.  Right? Right? We'll have a plot involving an evil clone right?

**Comment by Zireael07** [comment]
I <3 the dna_signature idea (I love any ideas that involve DNA in general, and this is a perfect marriage of a programming concept [UUID] and a real world concept [DNA])
