### ISSUE TITLE
Balance: MP-1350 seems too cheap compared to MP-1250 and MP-1500

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#12]
Here are the prices I get in-game:

* MP-1250: $1,237,612; 1.8 tons; 4 slots
* MP-1350: $435,408; 2.1 tons; 4 slots
* MP-1500: $1,804,050; 2.0 tons; 4 slots

For a mere 16.667% increase in weight, MP-1350 gives *more* power than MP-1250 *and* is cheaper.

Indeed, at a greater scale we can consider that the engine is carrying a lot more than just itself, and the 0.3 ton difference is tiny compared to the rest of the mecha's total weight.

MP-1350 should be either larger in slots or much much heavier, or the Advanced engines should be a lot lighter (like just 0.1 ton total, so that it's a noticeable boost in your mobility compared to high-output or standard engines).

**Comment by jwvhewitt** [comment]
I think there are a number of problems here, so I've addressed them all. First off, the shop display doesn't show HP for items, so it wasn't obvious that the High Output engines are more fragile than the Advanced engines. This has been changed. I've also lowered the cost for Advanced materials and increased the cost for high-power engines.
