### ISSUE TITLE
No-cockpit and multi-cockpit mecha

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#121]
While studying #119, I realized I could very easily edit a mecha with multiple cockpits or no cockpit at all.

Obviously a mecha with no cockpit cannot be used in mecha-scale combat.  So what should the game do in that case?  Currently it would crash in `GearHeadCampaign.get_usable_party` because `Mecha.load_pilot` would try to install the pilot into `None`.

A mecha with multiple cockpits is fine (`Mecha.free_pilots` would even work correctly), but currently we only consider one pilot per mecha.  And the single pilot gets loaded into the cockpit that a `sub_sub_coms` traversal would find last.

What's the best solution to this?

**Comment by AmkG** [comment]
My particular user story here is that we have a mobility bonus of +10 for head-mounted cockpits, similar to the +1MV/TR in previous games for head-mounted cockpits.  Unfortunately this is not displayed in the mecha engineering terminal, because the mobility bonus is applied only if there is a pilot, and most of the time the mecha engineering terminal mechs have no pilot (you can install one, but if you forget to remove the pilot before leaving the mecha engineering terminal, problems will occur in your game, especially if you used the player character).  You would never learn of this fact unless you played previous games (and even then, you might assume, as I did, that head-mounted cockpits have no mobility bonus because the MechEngTerm doesn't show any improvement in mobility when adding/removing head cockpits).

So at least part of my plan is to factor out `load_pilot` with a deterministic `get_cockpit` function.  The pilot is always loaded by `load_pilot` into whichever cockpit is found by `get_cockpit`.  Then modify the `calc_mobility` function to check `get_cockpit` instead of `get_pilot` (assuming you can only edit mechs in the MechEngTerm outside of mech combat, `get_cockpit` should always return the cockpit where `get_pilot` would be in combat).

To handle multiple cockpits, we can have `get_cockpit`, say, generate a list of all `Cockpit` gears in the mecha.  If there is more than one, we sort them by some deterministic function and return the first.  For example we could sort head-mounted cockpits first, or torso-mounted ones first.  Or leave the current code, which just always returns the *last* cockpit found.

Handling no-cockpits mech is harder.  Maybe the MechEngTerm refuses to exit when the mech has no cockpit, preventing any future crash in `load_pilot`?

**Comment by jwvhewitt** [comment]
There is a mecha viability checker that gets used on the meks loaded from design files, and that rejects any meks that have zero or multiple cockpits. This method could be used to check party meks prior to combat, or even added to the is_operational method.

**Comment by jwvhewitt** [comment]
Fixed. Design validity is now displayed in the info panels and checked before a mecha enters combat.
