### ISSUE TITLE
Character shared memories

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#125]
One thing I noticed in previous GearHeads is that characters hardly ever refer to events within the game that happened in the past.  They might refer to events in the backstory, but not to events that occurred in the game.  The guardian who joins up with you after you help them with the data chip in GearHead 1 never refers to that event ever again in any conversation or future event.

While researching about procedural story generation, I came upon the idea from [Lume](https://eis.ucsc.edu/papers/Mason_Lume.pdf):

* Events that change the relationship of two characters are recorded, with three possible descriptions: a long description ("the fire that burned down the house"), a short description ("the fire") and a negative description ("you let the fire burn down").

So maybe we should wrap the `expectation`, `relationship`, and `attitude` fields of the `Relationship` object into `get_expectation`/`set_expectation` et al.  The `set_expectation` et al method accepts two arguments, the new `expectation` value, and a tuple of the long/short/neg descriptions (or a proper classed object for better typing).

For example, suppose you got a lancemate challenge `DDLD_SortingDuel` and won, which changes the character's `attitude` to you into being `A_JUNIOR`.  This event can in the future be referred to:

* [you_made_me_change_my_attitude] "I challenged you and you showed me your superiority"
* [my_attitude_changed] "you one-upped me"
* [you_forced_me-to-change_my_attitude] "you completely crushed me after I challenged you"

So maybe in random `[News]` a character with a non-`None` `attitude` might randomly say "I've been thinking about that time [you_made_me_change_my_attitude], and I now think I am a better cavalier for it.", and if the character challenged you in the past in `DDLD_SortingDuel` zey would say "I've been thinking about that time I challenged you and you showed me your superiority, and I now think I am a better cavalier for it".

Possibly the descriptions themselves can be dialogue dictionaries like in `ghdialogue` as well, so that the character's personality may change how they describe the event as well.

Suppose in the future a lance development `Plot` makes this character evil (maybe the character has the `Criminal` tag and the local Mafia has asked them to betray you and steal your mecha or something), the character can say something like "You remember that time [you_forced_me_to_change_my_attitude]? Well... maybe you should have." as a parting shot before leaving you, and that would be rendered as "You remember that time you completely crushed me after I challenged you? Well... maybe you should have."

I think this would be good versimilitude and makes characters feel like, you know, actual characters, not just NPCs who follow you around and randomly do stuff.

**Comment by AmkG** [comment]
So let's plan the code.

First we need to ensure that plots and so on cannot change the `atttitude`/`expectation`/`role` directly, without providing a description of just what the heck happened to cause the change.  This means doing something like this:

```python
class Relationship(object):
    # blah
    @property
    def attitude(self):
        # back compat with existing savefiles
        dict = self.__dict__
        if "attitude" in dict:
            self._attitude = dict.pop("attitude")
        # just reflect self._attitude
        return self._attitude
    @attitude.setter
    def attitude(self, new_attitude):
        raise RuntimeError("Use set_attitude() method to set attitude")
```

Then the `set_attitude` function would accept the new attitude together with a dict containing the keys `you_changed_my_attitude`, `my_attitude_changed`, and `you_forced_me_to_change_my_attitude`, then extends the relationship's `grammar`:

```python
class Relationship(object):
    # blah
    def set_attitude(self, new_attitude, grammar):
        assert isinstance(grammar, dict)
        assert len(grammar.keys()) == 3
        assert '[you_changed_my_attitude]' in grammar
        assert '[my_attitude_changed]' in grammar
        assert '[you_forced_me_to_change_my_attitude]' in grammar
        self._attitude = new_attitude
        self.grammar.update(grammar)
```

For magic savefile back compatibility we make `grammar` a property like so:

```python
class Relationship(object):
    # blah
    @property
    def grammar(self):
        if not hasattr(self, '_grammar'):
            self._grammar = dict()
        return self._grammar
```

Finally we remove `role`, `attitude`, and `expectation` from the `__init__` method, in order to force lancemate joining plots to set those fields using `set_attitude`/`set_role`/`set_expectation` instead of just putting the relationship when starting their relationship with you.

Then we add tags `HasAttitude`, `HasRole`, `HasExpectation`, and modify `ghdialogue` to check the `relationship` for having non-`None` `aittitude`/`role`/`expectation` and consider those tags as existing as well, and to expand the grammar dictionary with the `relationship.grammar` as well.

Thoughts?

**Comment by AmkG** [comment]
It would be nice to also use `Singleton` tag classes instead of strings for e.g. `attitude`.

For example, a random conversation with a lancemate might say "So an acquaintance of mine asked about why I acted {attitude_adverb} to you, and I told 'em about how [you_made_me_change_my_attitude]."  So for example, the `A_JUNIOR` attitude would cause `{attitude_adverb}` to be "subordinately", and if the character is subordinate to you because you beat them at `DDLD_SortingDuel`, then the lancemate might say "So an acquaintance of mine asked about why I acted subordinately to you, and I told 'em about how I challenged you and you showed me your superiority".

```python
class A_JUNIOR(Singleton):
    label = "Junior"
    adverb = ("subordinately",) # npc _ did something to player
    adjective = ("subordinate",) # npc is a _ character to player
    noun = ("junior",) # npc is a _ of the player
```

Now suppose instead the attitude of the NPC is due to you giving the "I don't know, and besides you've proven yourself as a lancemate already" during `DDLD_JuniorQuestions`.  A plausible set of descriptions for this event could be:

* [you_made_me_change_my_attitude]: "you affirmed me as a valuable lancemate when I asked for advice about being a cavalier"
* [my_attitude_changed]: "you affirmed me when I felt lost"
* [you_forced_me_to_change_my_attitude]: "you fooled me into thinking I was valuable to the lance when I asked was being stupid about being a cavalier"

This leads to an `A_FRIENDLY` attitude:

```python
class A_FRIENDLY(Singleton):
    label = "Friendly"
    adverb = ("amicably",)
    adjective = ("friendly",)
    noun = ("friend",)
```

And the lancemate might say something like "So an acquaintance of mine asked about why I acted amicably to you, and I told 'em about how you affirmed me as a valuable lancemate when I asked for advice about being a cavalier."

Add more plot events that change character's attitudes towards the player, and the character will periodically pepper its conversation with references to things the player did, as a lasting effect on the game world.

**Comment by jwvhewitt** [comment]
I like the idea of changing the relationship tags to singletons and including dialogue grammar in there. My plan was to include a history field in the data dict of the relationship which would list important events in the PC/LM relationship; each history event would come with context data and text strings so it can be accessed as needed later.

Give me a bit to type this out in more detail.

**Comment by AmkG** [comment]
Waiting on this, BTW, wanna see what you plan for something like this kind of memory.

**Comment by jwvhewitt** [comment]
The relationship class contains a history list. The history records would include a textual description and a reaction score modifier, which would serve as a way of recording whether this is a good memory or a bad memory. The textual description should include at least two strings: the event from the PC's perspective and the event from the NPC's perspective, as well as maybe an abbreviated version that can be used by anyone. These descriptions can be incorporated into the lancemate's grammar (note that if a grammar token does not exist, the text generator will try to generate a different sentence that doesn't use it, so there is no need for all events/relationship tags to contain all possible grammar tokens).

This gives us a lot of possibilities. We can search the history to pick out bad events or positive events of a given magnitude. We can check the most recent history items to see if the relationship is going up or going down.

**Comment by AmkG** [comment]
So changes in `attitude`/`role`/`expectation` include a reaction modifier as well?

```python
    def set_attitude(self, attitude, reaction_delta, event_desc):
        if not isinstance(event_desc, EventDesc):
            raise Error()
        # blah
```

Then `EventDesc` would look something like:

```python
class EventDesc(object):
    def __init__(self, pc_view, npc_view, thirdparty_view):
       self.pc_view = pc_view
       self.npc_view = npc_view
       self.thirdparty_view = thirdparty_view
```

?

> This gives us a lot of possibilities. We can search the history to pick out bad events or positive events of a given magnitude. We can check the most recent history items to see if the relationship is going up or going down.

How would we express that in, say, a dialogue sentence?  For example, I want a positive recent event, because the NPC is a bit abashed about asking help from the PC and wants to steel zemself by reminding zemself that the PC is a nice person.  How do I express that?

**Comment by jwvhewitt** [comment]
The HistoryRecord would look something like:

`class HistoryRecord(object):
    def __init__(self,grammar,reaction_modifier):
        self.grammar = grammar
        self.reaction_modifier = reaction_modifier`

And the Relationship object would get some new methods for dealing with the history list. 'get_recent_positive' and 'get_recent_negative' would retrieve the most recent positive and negative memories of a given magnitude; either can of course return None. 'get_recent_trend' would return whether the most recent x history items are trending positive or negative. The relationship would probably also need a 'get_grammar' method to harvest grammar elements from the history records and the descriptors.

The history would not be explicitly tied to the relationship descriptors, but would often be used in concert with the descriptors.

The grammar harvested from the relationship attributes would be accessed like any other grammar tag; so yes, you could write something like "This is difficult for me to ask, but, then I remembered [recent_positive_event], so can I ask for $CREDITS to ransom my no-good brother?".
