### ISSUE TITLE
Player Character's Mecha suddenly disappearing from game

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#126]
Sometimes later in the game my starting mecha disappears after selling some other unrelated mecha.

Generally my starting mecha has been modified and is now piloted by one of my lancemates after I move on to another mecha.

In particular you normally can't sell a mecha that is currently being piloted by anyone in your lance, and it happens with the starting mecha of the player character *and* it is being piloted by a lancemate.  The lancemate then reverts to piloting their starter mecha.

I've encountered this in at least two different playthroughs.  The first time I thought I just made a misclick somewhere (selling at stores is unforgiving and you lose gears forever without any confirmation or undo).

It seems to happen while I'm moving around in Wujung, e.g. going between Allied Armor and Wujung Tires for better wheels and maybe Wujung Hospital to upgrade cyberware.

I haven't quite nailed down this weird behavior, maybe someone can chime in and see what I'm missing?

**Comment by jwvhewitt** [comment]
That can happen if the mecha is destroyed in combat and fails the recover roll; in such a case the lancemate will revert to using their own mecha. No idea what would cause it in-town.

**Comment by AmkG** [comment]
Well it was definitely in-town.  I was pottering around in the mecha eng term of Allied Armor and decided that I would upgrade from the A7800 Joust to one of the salvaged Dielancers, so I went to Wujung Tires to check for Lightened Wheels 6C to replace the wheels on the Dielancer, then when I returned to Allied Armor the A7800 Joust was gone and my lancemate went back to his starter mecha.

**Comment by AmkG** [comment]
It might not be tied to the player character's starting mecha, for that matter --- I just always start with an A7800 Joust because it has the best charge weapon among the starter mechs.  It could be something to do with full name sort order.

**Comment by AmkG** [comment]
Aww crap.  Happened again.  I was moving some equipment from an A7800 Joust (which my char was riding) in Allied Armor, then went to Wujung Tires to check for Wheels 5.  There weren't, so I thought to just swap around some equipment from the A7800 Joust, but when I checked at the MechEngTerm in Wujung my A7800 Joust was gone.

Looks like A7800 Jousts are cursed or something.  My char's starter mecha was an SDH-22I Iron Dielancer (a ridiculously OP start, incidentally, since it oneshots early game more often than a Heavyfoot, at 1/5 the price), so it looks like "First Mecha" here is first in full name sort order.

**Comment by AmkG** [comment]
It bit again!  This time I managed to somehow lose the [Heavyfoot Raider BuruBuru](https://github.com/jwvhewitt/gearhead-caramel/pull/149#issuecomment-655658142).  Sad.  I took some items off it, including engines and the weapons, then went and fought a final battle with some thugs, swung over to Wujung Tires, then I went to Allied Armor to buy some stuff and then... I checked the Mecha Engineering Terminal and it was gone.  All I got from it was a Raider Engine, Raider Heavy Gauss, and a Raider Armor 2C. :(

**Comment by AmkG** [comment]
It's also not the first-in-name-order that disappears, because my current mecha is an HMC-06G Ji Wolfram while the disappearing mek this time is a SAN-X9g Heavyfoot Raider BuruBuru.......... noooooooooo

**Comment by AmkG** [comment]
Yet another hit.  I was in a deadzone town with this salvaged Fulminate Dragon Musketeer.  I took out its engines and some items, planning to take its 8-volume legs to replace the 6-volume legs on my Haiho to get larger wheels.  I then went to Wujung to get Lightened Wheels 6C, bought a pair, then went to the MechEngTerm to swap the legs --- and the Musketeer was gone.  Darn it!  That was a 1M mech!

**Comment by AmkG** [comment]
Great, happened again.  This time my starting Wolfram disappeared.  I was in Allied Armor at the mech eng term moving stuff around to transfer from my starting Wolfram and moving to a new Gunslinger Daum.  Decided that my new Daum was too slow with size 5 legs (10 slots) and Lightened Wheels 6C, so decided to remove the Wolfram's legs to put into the Daum, and get Wheels 7 instead.  When I entered Wujung Tires, the HQ showed the Wolfram was gone!

It looks to me that the main issue has to do with Wujung Tires.  It seems to be the general trend that when I go decide to buy new wheels at Wujung Tires, there's a tiny chance one of my mechs disappears.  @jwvhewitt ?

**Comment by AmkG** [comment]
I think I've found it!  If you remove the engines from a mecha and then enter Wujung from any of its buildings, the mecha disappears!  This seems to trigger reliably for me.  Maybe something in the code to special-case entering Wujung?

**Comment by AmkG** [comment]
I might have traced it.  When moving between scenes, we call into `GearHeadCampaign.remove_party_from_scene`: https://github.com/jwvhewitt/gearhead-caramel/blob/1857574a960a89b7ab3869df0f707ffa7549fec5/gears/__init__.py#L567-L569

As seen above, it calls into `bring_out_your_dead`:

https://github.com/jwvhewitt/gearhead-caramel/blob/1857574a960a89b7ab3869df0f707ffa7549fec5/gears/__init__.py#L543-L546

Now, `is_destroyed` in `gears.base.StandardDamageHandler` just delegates to `is_not_damaged`: https://github.com/jwvhewitt/gearhead-caramel/blob/1857574a960a89b7ab3869df0f707ffa7549fec5/gears/base.py#L92-L93

For mecha, it specifically checks the engine! https://github.com/jwvhewitt/gearhead-caramel/blob/1857574a960a89b7ab3869df0f707ffa7549fec5/gears/base.py#L3319-L3328

I think it's rather bad behavior to completely destroy a mecha I am working on just because I removed the engine or torso temporarily while moving out.

Maybe the removal of mecha should only be done if we actually brought the mecha into combat, not when I've removed its engines in the MechEngTerm.

**Comment by jwvhewitt** [comment]
Great! I think the best solution would be to only get rid of destroyed mecha that are currently on the map; that way, bring_out_your_dead works as intended and the half-cannibalized mecha in your stash are safe.

**Comment by AmkG** [comment]
Would this work?

```python
    def bring_out_your_dead(self, announce=False):
        for pc in list(self.party):
            if pc not in self.scene.contents:
                continue
            if pc.is_destroyed():
                self.party.remove(pc)
```

**Comment by AmkG** [comment]
Hmm, does not work if a lancemate dies in combat though?  Hmmm.  Just do that `pc not in self.scene.contents` check for mecha?

**Comment by Zireael07** [comment]
Not sure if the PR has it (I couldn't grok all the changes in GH interface), but it would be much easier to spot the issue if there were a message on mecha being destroyed such as 'You fail to repair your %s, destroying it'

**Comment by AmkG** [comment]
Seems a good idea.

**Comment by AmkG** [comment]
Hmmm well the default is `announce=False`, which seems sensible to check if `announce=True` before announcing such a message.  And the bug triggers with `announce=False`.  Still, saying that a mecha was wrecked beyond recovery after a mission seems like a good idea.

**Comment by jwvhewitt** [comment]
I have added the pull request, and modified things so that announce_mecha (which should happen at the end of every combat) has been separated from announce_characters (which in mecha combat gets handled by the recovery plot right after battle, and in dungeons gets handled after every individual encounter).
