### ISSUE TITLE
Possible to enter mecha-scale combat with personal-scale Being

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#127]
Oh yeah.... feel my human-scale character's punch you 18-meter rogue mecha

![Screenshot from 2020-05-14 12-13-54](https://user-images.githubusercontent.com/3140/81891968-8c745780-95dc-11ea-9a87-4f381d1fe3b8.png)

To replicate:

* Start game and get to Wujung.
* Remove cockpit of your starter mech in Allied Armor.
* Go to Blue Fortress and ask for a mission.
* Go do the mission.

**Comment by jwvhewitt** [comment]
Fixed. Now you can't enter a mecha combat mission if you don't have any mecha. You can send your lancemates into combat if they have mecha but you don't. Also, the fix correctly deals with solo missions.

**Comment by jwvhewitt** [comment]
Just added another change so you won't get highway encounters if you don't have a mecha.
