### ISSUE TITLE
Really OP lancemate!

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#129]
![Screenshot from 2020-05-15 00-05-43](https://user-images.githubusercontent.com/3140/81958289-5a94dc80-9640-11ea-9193-ab8574d35eb1.png)

Legendary Body, Ego, and Knowledge, +9 cavalier skills, and the Zerosaiko *starter* mecha?  This character is way too OP.

Sure he comes a 18,750 credits but...

**Comment by AmkG** [comment]
I think stat generation should be made more "flat" distribution: even rank n00b npcs should have comparable statwise to the pc and veteran characters.  Skills and starter mecha being divergent based on rank is fine, but not stats.  After all, the player character zemself can train skills and buy better mecha, but can only modify stats via cyberware.

**Comment by jwvhewitt** [comment]
That's a good idea. I will do that.

**Comment by jwvhewitt** [comment]
Stat generation for random NPCs has been flattened.
