### ISSUE TITLE
`AttributeError: 'Armor' object has no attribute 'damage'`

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#13]
[fail.txt](https://github.com/jwvhewitt/gearhead-caramel/files/4493945/fail.txt)
[save.zip](https://github.com/jwvhewitt/gearhead-caramel/files/4493950/save.zip)

Was fighting against the commander in a Blue Fortress-given mission.

**Comment by AmkG** [comment]
Another instance with the same savefile: [fail.txt](https://github.com/jwvhewitt/gearhead-caramel/files/4493998/fail.txt)

**Comment by jwvhewitt** [comment]
Fixed.

**Comment by AmkG** [comment]
Please push fix?

**Comment by jwvhewitt** [comment]
Just pushed to the repository. I'm going to try to make a new release this weekend.
