### ISSUE TITLE
<pc punches Char>

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#130]
The name of the character is completely lowercase, and has no portrait:

![Screenshot from 2020-05-16 15-48-27](https://user-images.githubusercontent.com/3140/82114059-ea47a180-978c-11ea-9cdd-179ed9262616.png)

**Comment by jwvhewitt** [comment]
Fixed, kind of. When it's the player punching, there will still be no picture but the text is changed to <punch Char>. When a lancemate punches the picture will come up.
