### ISSUE TITLE
Strange backstory

### ISSUE THREAD

**Issue by xordspar0** [jwvhewitt/gearhead-caramel#134]
![Screenshot from 2020-05-18 10-07-09](https://user-images.githubusercontent.com/2390950/82229020-7e317e80-98ef-11ea-8fe7-b0f1cc78f3f6.png)

> I was betrayed by my master so I swore to never let down my guard. Moral of the story: we're all in this together.

Should this be possible? Am I expecting too much of the backstory generator, or should it be more coherent? Or maybe my character is really tough and wants to show that we're all in this together despite a bad experience in his past?

**Comment by AmkG** [comment]
> Or maybe my character is really tough and wants to show that we're all in this together despite a bad experience in his past?

This.

**Comment by jwvhewitt** [comment]
The reading is correct, but you're right that the text is weird. I have changed the Fellowship branch from the Betrayal event to better reflect what's going on.

**Comment by xordspar0** [comment]
Cool, thanks. You've both been doing really impressive work, keep it up. 👍
