### ISSUE TITLE
Unsellable gear

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#14]
I have a gear in my Field HQ that I somehow can't sell.

Here is the item:

![Screenshot from 2020-04-18 01-17-58](https://user-images.githubusercontent.com/3140/79596106-8d67b580-8112-11ea-9833-56daeef624c4.png)

When talking to a mechanic to "Sell Items":

![Screenshot from 2020-04-18 01-19-34](https://user-images.githubusercontent.com/3140/79596203-bb4cfa00-8112-11ea-804b-780b5fcddf67.png)

When talking to a mechanic to "Sell Mechs":

![Screenshot from 2020-04-18 01-20-41](https://user-images.githubusercontent.com/3140/79596283-e2a3c700-8112-11ea-9414-169637978e59.png)

Attached save.zip: [save.zip](https://github.com/jwvhewitt/gearhead-caramel/files/4494351/save.zip)

**Comment by AmkG** [comment]
FWIW it was originally on a mech currently being piloted by Doba.  I swapped out the Plasma Spear with an Ion Spear from the salvaged Dielancer.  Is the reason that the Plasma Spear is not sellable is because it is "owned" by Doba?

**Comment by jwvhewitt** [comment]
Yes, that's the reason. This should be indicated on the FieldHQ display. I just added ownership info for non-mecha items to the FieldHQ display. I have, for now, also disabled access to the inventory of lancemate-owned mecha.
