### ISSUE TITLE
Tarot password not working?

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#159]
![Screenshot from 2020-08-05 21-27-15](https://user-images.githubusercontent.com/3140/89418477-ae582300-d762-11ea-844c-21e6eef7c34f.png)

But:

![Screenshot from 2020-08-05 21-28-03](https://user-images.githubusercontent.com/3140/89418493-b31cd700-d762-11ea-9d81-c961cdb855ee.png)

Save file: [rpg_Colemaia.sav.zip](https://github.com/jwvhewitt/gearhead-caramel/files/5028657/rpg_Colemaia.sav.zip)

Unless I'm missing something about what the game expects me to do....?

**Comment by jwvhewitt** [comment]
This was a bug in v0.540, fixed in the most recent commit. I misnamed a function.
