### ISSUE TITLE
Attack Attributes ideas

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#160]
`PowerDrain` is only allowed on `EnergyWeapon`/`MeleeWeapon`.  If it hits, it also drains significant amount of power (say 4x to 6x the power cost of a `BeamWeapon` attack of equivalent damage, or 5 damage) from the target mecha (if it has any) and regenerates half (or 1/4?) the amount drained to the attacker.

`IgniteAttack` replaces `BurnAttack` on `EnergyWeapon`/`MeleeWeapon` (`BurnAttack` remains but is only allowed for ranged weapons/ammo).  Ignite has the same `Burning` enchantment effect, but also has a chance that a random selected `BallisticWeapon`/`Missile` (and maybe `Chem` as well?) on the target will lose between 1 to remaining - 1 ammo.  No effect (beyond `Burning`) if the target has no appropriate weapons/missiles.  For back-compatibility with older savefiles we can upgrade `BurnAttack` to `IgniteAttack` when we see it on an `EnergyWeapon` / `MeleeWeapon`.

-----

More generally, I am thinking of advancement possibilities for melee mecha vs ranged mecha.

The major advantage that ranged weapons have is the possibility of `BurstFire5`/`VariableFire5`,  While it's true that they are limited by ammo/power, in general ammo and power limits are high enough that the burst value doesn't matter.  For example the Daum's Bolt Cannon has a whopping 250 shots, and with `BurstFire5` it can fire 50 times in combat without switching ammo (and there seems to be no way to switch ammo in combat?).  A ranged weapon with `BurstFire5` damage 5 can theoretically do up to 25d6 damage, if my understanding of the code is right.

The best melee weapons can do would be 10d6 due to only having `FastAttack` which is equivalent to burst value 2.  That is only 40% of the maximum theoretical damage a ranged attack can do, and melee weapons are short-ranged.

On the other hand, melee is much less affected by cover (though that is a bit of a wash, since cover is mostly symmetric unless using Take Cover / Spot Behind Cover) and sensor and too far/near issues.  Another advantage is that a melee weapon can get `Flail` (ignores Parry and Block at the cost of losing Parry for that specific weapon only) and `Smash` (ignores evade at the cost of spreading out the damage among multiple modules).  A `Flail, Smash` weapon like Wrecking Ball gets 100% chance to hit even against ridiculously mobile targets like Chameleons.

So perhaps how melee weapons can advance would be to add some fairly interesting, and tactically-significant, effects on melee weapons, which apply when they hit, and having weapons that do not deal a lot of damage but instead cause some fairly interesting effects.  For example a Shock Rapier can instead be a 1-5-1 weapon (low damage and penetration, but high accuracy) with a further `Accurate` modifier and `PowerDrain` modifier (instead of the existing `OverloadAttack` modifier); it would be quite useful against agile mecha with tons of energy and beam weapons, but not much else.  Similarly a Heat Axe would now potentially make `BallisticWeapon`-heavy mecha quickly useless by igniting their ammo, instead of just being an interesting alternative to a Mecha Sword (and obsoleted by an Ironbreaker Longsword or Wrecking Ball).

Thus, I propose the above attack attributes, which I think are interesting enough that a minmaxer might go for them (and might even field more than just a charge + melee weapon, they might have a charge weapon+`PowerDrain` weapon+`IgniteAttack` weapon).

Thoughts?  Also, other ideas on interesting effects we can have on melee weapons?

**Comment by jwvhewitt** [comment]
In GH1 and GH2, all melee/energy weapons have the chance to score multiple hits depending on the character/s Speed and skill level. That's something that would be easy enough to bring back. Also, I'm right now in the process of giving melee attacks a damage bonus based on Body stat (for Beings) or module size (for Mecha).

Another possibility: allow melee weapons to make attacks of opportunity or counter-attacks like in D20 RPGs and the Super Robot Wars games. Any enemy attempting to move through a tile guarded by a model is automatically attacked. In D20 there's a limit of one attack of opportunity per round, with certain special effects allowing more.
