### ISSUE TITLE
Solar Navy conversation in an infinte loop

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#165]
So I strike up a conversation with a Solar Navy commander or whatever:

![Screenshot from 2020-08-08 22-21-49](https://user-images.githubusercontent.com/3140/89712792-c2e82580-d9c5-11ea-8a45-0e9170315327.png)

![Screenshot from 2020-08-08 22-21-57](https://user-images.githubusercontent.com/3140/89712795-c7144300-d9c5-11ea-970f-d73fac52a1b1.png)

And I enter in a conversation that won't exit, circularly asking about the same two topics over and over again.

**Comment by jwvhewitt** [comment]
I have closed this loop. It's possible that other loops remain.
