### ISSUE TITLE
lousy memo message?

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#166]
![Screenshot from 2020-08-08 22-57-28](https://user-images.githubusercontent.com/3140/89713892-67219a80-d9cd-11ea-92bb-8a2e222d10cf.png)

So... who *is* she?

**Comment by jwvhewitt** [comment]
Guess you'll have to go to Town Hall to find out. I have fixed the memo in question to include not only her name, but what "it" is.
