### ISSUE TITLE
Melee Multiattack OP, plz nerf

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#168]
A cybered-up high-Speed character just decimates opponents with a melee mech, oneshotting BuruBuru or even Claymores with a Flame Knout.

This makes melee mildly unsatisfactory. Ranged attack considers terrain because obstructions make it harder to hit enemies, and ranged vs ranged combat is mostly manoeuvring terrain to keep cover low for the target mecha while keeping under cover to the other enemy mecha.  Charge attacks make you pick strong attention to terrain and enemy position, since obstructions prevent charging and you want to charge between two opponents as much as possible to maximize your Charge-based bonuses.

But non-Charge-based melee can almost entirely ignore terrain, and gets performance similar to Charge-based melee (oneshotting an enemy or two on your first turn) before the introduction of melee multi-attack.

In my current playthrough I have a Haiho with a Flame Knout and it's disgusting, it just utterly decimates enemy mechs, yet that Flame Knout is pretty much spare change. My character has Reflexes 21 and Speed 19 (maxed Reflexes and Speed at the cost of Ego and Craft and Perception, plus an Adrenaline Heart) and +2 Mecha Fighting from a Spinal Pilot Link.  It feels worse than the OP Iron Dielancers of the past, because at least Charge is strategically interesting relative to the map terrain, and we nerfed that by greatly boosting Charge price.  I have a Giant Drill sitting unused in my HQ, because it's a heavy weapon and greatly reduces the speed and mobility of my Haiho, I'm starting to wonder if I should just remove one arm off the Haiho and have it just use the Flame Knout (I have a Grounding Whip as well, but one or the other will just one-shot enemies anyway so the Ignites Ammo / Drains Power attributes don't even come into play, and having multiple melee weapons is unuseful at this point; I should probably just get a Wrecking Ball for the 100% to-hit and even higher damage over the Flame Knout).

Some ideas:

* Completely remove melee multi-attack, and reduce the MP cost of Fast Attack from 3 to 1, and reduce the MP cost of Multi Wielded from 1 + numweapons to numweapons - 1, and add more Mutli-wielded and Fast melee weapons in shops and mecha (e.g. a purchasable Mecha Daikatana similar to the Mecha Sword but with a lower accuracy, loss of Defender, and Multi Wielded).
* Alternately, if we would have a melee multi-attack, do an additional Stamina roll: roll a number between 1 to max stamina, and if the result is less than or equal to current stamina, continue with the mutli-attack, else just attack once.  If we multi-attack, spend 1 stamina.
* Or just generally lower the chances of melee multi-attack, especially those beyond 2 attacks.

**Comment by jwvhewitt** [comment]
Just modified this. Multiple hits are less likely, and more than 2 hits are much less likely. Also, I reduced the base damage bonus for mecha melee attacks from (module size - 1) to (module size // 2).

**Comment by AmkG** [comment]
Hmmm.  Even after the nerfing, it seems to me (looking purely at code, have not playtested yet) that Flail weapons have a much better chance of rolling additional attacks, due purely to reducing the number of defenses tried, which prevents `hi_def_roll` from going too high.

Also, given that `hi_def_roll` starts at 50, it seems there is no chance at all of getting 4 or 5  multi-attacks without additional modifiers like Immobilized or Sneak Attack.  Hmmmm....

**Comment by AmkG** [comment]
Playtesting, melee still seems overpowered.  The Wolfram's Pickaxe, with a focused-Reflexes+Speed character, and with the Heavy Actuators 5 moved to the arm wielding the Pickaxe, gives performance on par with the Daum's Bolt Cannon.  Sure the Wolfram has to close in, but it can one-shot in your first turn, whereas the Daum's Bolt Cannon will often require at least 2 moves firing and sometimes a third and fourth.  Yet the Wolfram is a starter whereas the Daum is something you'll have to build up funds to.

I'm still getting x3 reasonably often now, though the amazing x4 and x5 don't happen yet, but then my current character hasn't been as heavily cybered as in the previous test with the Haiho (which was much more ridiculous).

It seems to me with how frequent I get x2 and x3, the `num_hits` is quickly saturating the `max_attacks`.

In #160 my main concern was with the *later* part of the game where the player has access to BurstFireN ranged weapons without getting similarly multiattack for melee.  So it would be best to enable multiattack for characters with higher skills, and discount Speed.

How about this?

```python
    max_attacks = 1 + max(0, originator.get_stat(self.att_skill) // 2 - 4 + originator.get_stat(stats.Speed) // 8)
```

With the above, for a "normal" character with 8->15 speed,  they start getting a chance for a second attack at Mecha Fighting +8, and get x3 at Mecha Fightning +10 etc.  For a dedicated-speed character with 16->23 speed, they start getting a second attack at Mecha Fighting +7, one level lower, and get x3 at Mecha Fighting +9 etc.
