### ISSUE TITLE
Melee multiattack **still** OP, plz nerf

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#172]
Not sure if you saw this comment here: https://github.com/jwvhewitt/gearhead-caramel/issues/168#issuecomment-674487654

Multiattack is still too OP.  I have a lance of two Secutors (whose Arena Cannons are fairly OP themselves, which suggests to me we need to boost up Burst costing even more: the Daum and Secutor Burst weapons are unfairly cheap for the amount of damage they spit out) and a Musketeer.  Prior to me getting a Gunslinger Daum from salvage, I was working a modified Wolfram mecha (put the Heavy Actuators 5 in the arm with the Pickaxe, remove the Armor 5 from that arm, replace it with the Armor 2 from the cockpit (which is in the fairly well-armored Torso so it's an OK risk to take)), and if I had the Secutors stand back and shoot their Arena cannons they had about the same performance that Wolfram mecha (which I might add had just the stock equipment plus 2x Lightened Wheels 6C, which are very cheap).  The Secutors get much better performance if I have them dive in and melee with their Mecha Wreckers.

They just dive in and one-shot everyone, with little to no risk from counterattacks.

Charge is even more ridiculously OP now as well, being a melee attack after all.

My char has 18 Reflexes and 18 Speed, and had Mecha Fighting +4 at the start (is at +7 now).  Yes, it's a dedicated-melee char, but still.  My sense is that melee multiattack is too OP to the point that getting an army of Haihos with  a single very powerful melee weapon each (Wrecking Ball, for example, I imagine would get similar performance to Mecha Wreckers) and with one arm removed (to cut down on weight while evading incoming fire) might be the best early-to-midgame strategy.

**Comment by jwvhewitt** [comment]
I have toned it down again, and upped the cost, mass, and volume modifiers for Flail. I wonder if damage in general is too high in comparison to health? I think the way things are currently tuned, weapons do more damage compared to health than they did in previous GearHead games. A Damage 3 weapon, which is pretty common for main armaments, is capable of one-shotting enemies pretty regularly with good skill. Damage 4 and 5 weapons do one-shot kills even more dependably. It might be a good idea to return to GH1/GH2 damage levels where a regular hit isn't necessarily catastrophic but a high hit roll can get bonus damage (currently no such thing as a critical hit).

**Comment by AmkG** [comment]
That might be true --- I sometimes get surprises where my full-health mecha is one-shotted, and the mobility/armor tradeoff is a hard one to balance on my own mecha.

**Comment by AmkG** [comment]
The increase in health certainly makes melee feel better, so far.  It also represents a fairly large drop in ranged effectiveness as well.  This means increase in usage of power and ammo, which is fine, I think.

It also makes the game a good bit harder, as predicted --- you have more enemies than allies, usually.  You also run the risk of running out of ammo/power, with no way (that I know of) to disengage from combat --- I think you need to allow the lance to (try to) rush to the exit in combat mode and leave combat, and maybe also allow an immobilized mecha to self-destruct.
