### ISSUE TITLE
Can do action, then move, then action

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#18]
How to replicate:

* Have some skill that needs you to be right next to someone, or a melee or very short range weapon.
* For your first turn, make some action: move (up to 1 turn), OR any action you can do without moving.
* For your second turn, select some action that would require you to move (e.g. repair a mech that is not adjacent to you).

For the second turn, you are able to move and then perform the action.

It's possible this is a deliberate rule, but it should probably be clarified somewhere.

**Comment by jwvhewitt** [comment]
Clarified by the action clock.
