### ISSUE TITLE
`DDLD_SharingMyInfo.GET_MACGUFFIN` never triggers for me

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#189]
https://github.com/jwvhewitt/gearhead-caramel/blob/4f81375efa227585e4e8d8bb76a7c21eea6f2250/game/content/ghplots/dd_lancedev.py#L1122-L1128

I've encountered this plot twice in two separate playthroughs, the `GET_MACGUFFIN` code never triggers for me.  Maybe it is because it called `proper_non_end` as soon as you respond in which case the plot is no longer active to receive this trigger?

FWIW I tend to savescum on personal-scale dungeons (I'm in this game for the 18-meter rogue mecha), is that relevant?

**Comment by jwvhewitt** [comment]
Solved it. The trigger method is supposed to be named MACGUFFIN_GET, not GET_MACGUFFIN. The element ID comes first and the trigger type comes second.
