### ISSUE TITLE
Pedantic: A "Morning Star" is not a ball-and-chain weapon

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#19]
xref: https://en.wikipedia.org/wiki/Morning_star_(weapon)

> The term is often confused with the military [flail](https://en.wikipedia.org/wiki/Flail_%28weapon%29) (fléau d'armes in French and Kriegsflegel in German), which typically consists of a wooden shaft joined by a length of chain to one or more iron-shod wooden bars (heavy [sword](https://en.wikipedia.org/wiki/Sword) pommels have also been used as weights).

Probably `Mecha Morningstar` should be `Mecha Flail` if it is to be described as a ball-and-chain weapon.

**Comment by AmkG** [comment]
Or `Mecha Kriegsflegel`

**Comment by jwvhewitt** [comment]
My years as an academic proofreader have left me with a deep respect for petty pedantry. I have changed the name to Wrecking Ball, but have written down Kriegsflegel for possible future use.
