### ISSUE TITLE
Missing DLL in Windows build

### ISSUE THREAD

**Issue by tinyrodentprime** [jwvhewitt/gearhead-caramel#201]
This is the error I get.
![image](https://user-images.githubusercontent.com/43912414/104749906-5a923280-5721-11eb-91c7-8dbb05f1a440.png)

**Comment by jwvhewitt** [comment]
The problem isn't really the missing dll, it's that Python 3.9 no longer supports Windows 7 and earlier. What version of Windows are you using? I can try rolling back the Python version in build, but I don't think I can go any earlier than 3.7.

**Comment by jwvhewitt** [comment]
Try release v0.612b, see if it works. https://github.com/jwvhewitt/gearhead-caramel/releases/tag/v0.612

**Comment by tinyrodentprime** [comment]
Right you are, it's Windows 7. But v0.612b seems to work fine, thanks!
