### ISSUE TITLE
In Mecha Engineering Terminal, editing the Name changes the Designation instead

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#25]
So I change the name of one of my mechs:

![Screenshot from 2020-04-20 14-10-39](https://user-images.githubusercontent.com/3140/79719795-e2bde580-8311-11ea-898b-c9ea8ccfe78c.png)

Then I exit, then edit the same mech again:

![Screenshot from 2020-04-20 14-10-51](https://user-images.githubusercontent.com/3140/79719819-ec474d80-8311-11ea-959a-7a8f60a12b7e.png)

**Comment by AmkG** [comment]
Looks like this?

https://github.com/jwvhewitt/gearhead-caramel/blob/f3c67f9a562b133b20b639c4a0162da0c8c348a3/game/geareditor.py#L191-L193

**Comment by jwvhewitt** [comment]
Yes, that's it.

**Comment by AmkG** [comment]
Right right. I wanted to change mech names because I had several of the same type, and I color-code them according to purpose (melee, support/artilery), and I had two melee-line Corsairs...
