### ISSUE TITLE
Idea: Allow non-Weapon components to be Integral

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#32]
It might make sense to allow non-Weapon components to be Integral to the module they are installed on.

Such integral components might be cheaper, lighter-weight, and/or require fewer slots.

For example, a high-tech mecha might be made cheaper because it has a relatively high-output engine that is integral to its torso, so while it might make a better-than-average early-game mecha, it cannot be upgraded to keep up with the late-game.

This is probably properly done by creating a `Component` class containing the `integral` field, and having `Armor`, `Shield`, `Engine`, `Gyroscope`, `Cockpit`, `Sensor`, `MovementSystem`, `EWSystem`, `Weapon`, and `Launcher` inherit from `Component`, with similar changes in the gear editor.

Is this a good idea?

**Comment by jwvhewitt** [comment]
It would be a good idea to have other items be integral, but I'm not sure right now the best way to do it. Each type of gear has its own volume calculation. The simplest thing to do would be to give each part type that can be integral its own integral property and write the volume modifier right into the volume method. A component class would basically have to do the same thing, and it would add an extra layer of complexity on top, so I think having each component define its own integral property is the right way to go.

Armor, Sensors, MovementSystems, Engines, Gyroscopes, Cockpits, and EWSystems would all benefit from being able to be integral. Shields can't be installed internally so they wouldn't. A Launcher's volume determines how many missiles it can hold, so an integral Launcher would be functionally worse than a Launcher one size smaller.

**Comment by AmkG** [comment]
We could use the same pattern as for cost and mass: have a `base_volume` that is overridden in practical gears, and `BaseGear` `volume` just calls into `base_volume`, and have `Component` override `volume`:

```python
class BaseGear(blah):
    # blah
    base_volume = 1
    @property
    def volume(self):
         return self.base_volume

class Component(BaseGear):
    # blah
    @property
    def volume(self):
         normal_volume = super(Component, self).volume
         if self.integral and normal_volume > 1:
             return normal_volume - 1
         return normal_volume

class Armor(Component, blah):
    # blah
    @property
    def base_volume(self):
        return self.size
```

Practical gears rename their `volume` methods to `base_volume`, gears we decide we want to make integral-able derive from `Component` instad, and you unify all `integral` handling to `Component`.

**Comment by AmkG** [comment]
Hooking into `self_cost` and `self_mass` allows `Component` to adjust cost and mass as well.  So for example integrated components might get a cost discount due to not being modularly moveable to other modules.

**Comment by jwvhewitt** [comment]
That would work. I was concerned about multiple inheritance not being able to guarantee the execution order of overridden methods, but with Component as a subclass of BaseGear that wouldn't be an issue.

**Comment by AmkG** [comment]
Okay, I'm working on this now.  The lack of dedicated part editors for cockpits and gyroscopes stymied me a little but I can probably just add them to `CLASS_EDITORS` right?

**Comment by jwvhewitt** [comment]
Yes.
