### ISSUE TITLE
`get_a_room() missing 1 required positional argument: 'self'`

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#38]
[fail.txt](https://github.com/jwvhewitt/gearhead-caramel/files/4524605/fail.txt)

[save.zip](https://github.com/jwvhewitt/gearhead-caramel/files/4524609/save.zip)

Not sure if this is savefile incompatbility, but the game was started prior to the recent "can have multiple room type" change, then loaded afterwards.

**Comment by AmkG** [comment]
Looks like savefile incompatibility: a new savefile works just fine.

**Comment by jwvhewitt** [comment]
Yes, it's a savefile incompatibility- specifically, if you have any missions prepared but not yet started, you'll get the error upon entering the mission.
