### ISSUE TITLE
Door leading nowhere

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#39]
![Screenshot from 2020-04-24 03-34-54](https://user-images.githubusercontent.com/3140/80141865-cef9d400-85dc-11ea-89b6-303ffc0e1eda.png)

[save.zip](https://github.com/jwvhewitt/gearhead-caramel/files/4524813/save.zip)

**Comment by jwvhewitt** [comment]
I have hopefully fixed this problem. At the very least I have fixed one problem that could lead to rooms being blocked off like this.
