### ISSUE TITLE
Strange invisible raised land

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#41]
I can't see anything in this part of the map:

![Screenshot from 2020-04-24 16-31-05](https://user-images.githubusercontent.com/3140/80192153-59781d00-8649-11ea-9487-a779ded025ec.png)

Targeting shows that some parts of the land are actually raised, though honestly I can't find any visual indication or hint that there is raised land:

![Screenshot from 2020-04-24 16-32-10](https://user-images.githubusercontent.com/3140/80192210-6f85dd80-8649-11ea-8620-4ee0fb3a020a.png)

**Comment by AmkG** [comment]
[save.zip](https://github.com/jwvhewitt/gearhead-caramel/files/4527872/save.zip)

**Comment by jwvhewitt** [comment]
It was solitary dragon's teeth mountains being displayed incorrectly (as in, not at all). Fixed.
![GHC_SingleDragonTeethInYourArea](https://user-images.githubusercontent.com/1691593/80379727-70cd3980-88d9-11ea-95ce-d80ba8c84081.png)
