### ISSUE TITLE
The bookshelf in Allied Armor can block a doorway, which prevents the bookshelf from being accessed

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#42]
![Screenshot from 2020-04-26 14-52-12](https://user-images.githubusercontent.com/3140/80300249-979e4980-87cd-11ea-9152-eef51517feb4.png)

Clicking on the bookshelf will instead move you to the location of the door.

**Comment by jwvhewitt** [comment]
You can still use the bookshelf by right clicking on that tile, but you're right it shouldn't be putting the bookshelf there anyhow. I'll see what's going on.

**Comment by Zireael07** [comment]
Hidden doorway, I suppose? There's a lot of examples of doors hidden in/behind bookcases in fiction... :wink: :wink:

**Comment by jwvhewitt** [comment]
The trouble is that that bookcase already contains a hidden doorway, but now we have a hidden doorway sharing the same tile with a non-hidden doorway!

**Comment by jwvhewitt** [comment]
I think I have fixed the bug.

**Comment by AmkG** [comment]
> The trouble is that that bookcase already contains a hidden doorway, but now we have a hidden doorway sharing the same tile with a non-hidden doorway!

SPOILERS!!!

**Comment by Zireael07** [comment]
Dooorception xDDD
