### ISSUE TITLE
Can salvage enemy mechs but not own?

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#44]
This line of code seems to suggest that mecha will be salvaged only if it is an enemy, meaning the player is somehow unwilling to salvage its own mechs if they are destroyed:

https://github.com/jwvhewitt/gearhead-caramel/blob/dbdb37fb8ebbaeb976172ff97ee9d13e710d4251/game/content/adventureseed.py#L331

This seems fairly strange.  Maybe not allow to salvage allied mechs but be willing to salvage those owned by the player at least?

**Comment by jwvhewitt** [comment]
Lance mecha (and characters) get a recovery roll in the bring_out_your_dead method of the GearHeadCampaign, in the gears/__init__.py module.
