### ISSUE TITLE
Crash due to `RecursionError` on `deepcopy` function

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#5]
[fail.txt](https://github.com/jwvhewitt/gearhead-caramel/files/4482761/fail.txt)

Game keeps crashing on me in Linux.

Rather than use a recursive `deepcopy` it might make sense to instantiate the "recursion stack" as a set of nested objects, then use a flat loop that pops off the recursion stack once an object is completely instantiated.  This way you can get around the `RecursionError` limit.

Alternately you could try to use completely immutable objects when transferring scenes, which IMO makes more sense, as it would allow sharing of data and reduce your memory footprint.

**Comment by AmkG** [comment]
`Python 2.7.17` if it is relevant.

**Comment by AmkG** [comment]
This suggests increasing the recursion limit, but this might not make a lot of sense: better to just use an algo which does not recurse: https://stackoverflow.com/questions/18697641/runtime-error-with-copy-deepcopy-in-python

**Comment by jwvhewitt** [comment]
Does the crash happen all the time or just in a particular place?

**Comment by AmkG** [comment]
It happens in various places, usually during combat but not always.  Often it happens when I'm moving my mouse over a target.

**Comment by AmkG** [comment]
So I tried using `sys.setrecursionlimit` but just now when I was switching weapons my CPU hung at 100% for a long time, so it seems not a solution.  Probably redesigning to completely avoid deepcopy might be better.

**Comment by jwvhewitt** [comment]
I think I've found and solved the cause of this problem. I am going to mark this as closed for now.

**Comment by AmkG** [comment]
Have not replicated it since latest changes so far, so maybe okay?
