### ISSUE TITLE
Giant Drill seems a bit cheap for its power

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#53]
In my game Giant Drill is just $16,156, but in my early-game playtesting it can one-shot most enemies, and the Charge attack gives bonus accuracy to compensate for the base weapon's inaccuracy.  For reference, a Heavy Gauss Rifle similarly is an early-game one-shotter (and it's less likely to one-shot, due to its lower penetration than Giant Drill) and is in the $700,000 ~ $850,000 range.  It feels as if Giant Drill can be 10x more expensive and it would still be a good buy (use Wheels from Wujung Tires for better DPR-to-size and DPR-to-weight, install it instead of mounting on a hand and remove the hand to reduce weight and bump your DPR, reduce armor to shave off more weigh, and the Charge range can start being competitive with ranged weapons).  The Beam Scourge is in the $75,000 ~ $85,000 range, and while useful for the Intercept, is a far less powerful melee weapon (I just buy it for the Intercept and high accuracy which is useful if it's hard/impossible to charge with the Giant Drill).

Against this, we still need to keep the Trailblazer and Joust prices down, so just bumping up cost computations for `ChargeAttack` is not good.  The Trailblazer Plasma Spear in particular is a particularly bad charging weapon; it's only really useful for moving the trailblazer in a straight line.

**Comment by AmkG** [comment]
Here's an alternative proposal:

* Keep the current basic equation: damage^2 * (accuracy + 1) * (penetration + 1) * (((reach^2 - reach) / 2) + 1)
* Instead of attack attributes multiplying the final cost of the above equation, attack attributes can modify the damage, accuracy, penetration and reach, used *only* for the cost equation.
  * For example, `ChargeAttack` would *add* to the reach and accuracy of the cost equation, which reflects the fact that it effectively makes the weapon a ranged one.
  * `Accurate`, `Flail` would add to accuracy.
  * `ConeAttack`, `LineAttack`, `Blast`\*, `BurstFire`\*, `VariableFire`\*,  add to damage.

We probably also need to consider how high-penetration high-damage weapons are costed.  Damage and penetration are particularly powerful.

**Comment by AmkG** [comment]
Some more observations:

* A relatively-lousy weapon with lots of attributes (such as Beam Scourge, which while a "good" weapon even for its price, is pricey relative to Giant Drill, which is an awesome weapon 1/5 the price of a Beam Scourge).
  * Maybe instead of multiplying the modifiers, add them together?  I.e. instead of `mult *= aa.COST_MODIFIER` it should be `mult += aa.COST_MODIFIER - 1.0`.  Currently a weapon with two `COST_MODIFIER = 1.5` attributes would have a final `mult` of 2.25, whereas using the additive version we get a `mult` of 2.0.  Beam Scourge currently has 2.5 * 1.5 * 2.5 = 9.375, whereas with additive `mult` it would be 1 + 1.5 + 0.5 + 1.5 = 4.5, halving its price.
* A comment in the cost equation mentions that reach is "so important".  With Charge, reach is significantly less important: in a reasonably open space, a highly speed-optimized mecha can attack up to twice the distance of its movement range, a feat that even the most long-range weapons will find difficult to match simply because of practical issues with aiming at a distance, whereas Charge removes a good amount of the distance-based issues.  Sure Charge is less useful in places with lots of terrain detail, but meh: Giant Drill still rocks, and it's a hundred times cheaper than a Nova Storm Buru Buru.
  *Maybe any weapon of reach 1 or 2 (i.e. melee and melee EXTEND) should be treated as reach 3 at least for price considerations?  And/or bump up the exponent on damage, reduce the exponent on reach?

**Comment by jwvhewitt** [comment]
I have changed the base weapon cost by adding quadratic factors that only kick in for high Accuracy, Penetration weapons. Also, I've increased the cost multiplier for ChargeAttack from 1.5 to 2.5. Since the GearHead Caramel system is so different from previous GearHead games, we are going to have to adjust the numbers a lot as we slowly move towards balance.

New weapon cost formula:
            (self.COST_FACTOR * (self.damage ** 2) *
            (self.accuracy ** 2 // 10 + self.accuracy + 1) *
            (self.penetration ** 2 // 5 + self.penetration + 1) *
            ((self.reach ** 2 - self.reach) // 2 + 1)) * mult

**Comment by AmkG** [comment]
Not so certain.  Giant Drill is now $52,800 raw cost from the off-game mecha editor, while Beam Scourge is now a whopping $120,000.  Giant Drill is now better-priced for its sheer power, but Beam Scourge is still overpriced relative to Giant Drill; I'd value Giant Drill more than Beam Scourge, because I can always replace Beam Scourge with a LAS-5 Intercept and a Flame Knout or Heat Axe or Mecha Sword, but the sheer power of Giant Drill in the all-important Charge position means only Ion Lance is a good competitor for it (and I'm still leaning a bit more towards Giant Drill due to its *combination* of high damage *and* high penetration).

I think the sheer number of attributes Beam Scourge has is makes it overpriced (only Ion Lance has as many attributes, and it isn't for sale so any mispricing it has is not visible); maybe just use the additive for `mult`?

```python
    @property
    def base_cost(self):
        # Multiply the stats together, squaring damage and range because they're so important.
        mult = 1.0
        for aa in self.attributes:
            mult += aa.COST_MODIFIER - 1.0
        return int(
            (self.COST_FACTOR * (self.damage ** 2) *
            (self.accuracy ** 2 // 10 + self.accuracy + 1) *
            (self.penetration ** 2 // 5 + self.penetration + 1) *
            ((self.reach ** 2 - self.reach) // 2 + 1)) * mult
        )
```

This gives identical results to current code when the weapon has a single attribute, but lowers the cost of weapons with multiple attributes.

Really, though, "damage is king" and should probably have a bigger effect than reach...

**Comment by AmkG** [comment]
With the above code, here's what I get as raw price:

* Beam Scourge: 57,600
* Wrecking Ball: 24,000
* Giant Drill: 52,800
* LAS-10 Laser Cannon: 285,120

Beam Scourge still seems overpriced relative to Giant Drill (I'd value Giant Drill more).  And melee weapons in general seem underpriced to ranged weapons.

So here's a further proposal:

* For `ChargeAttack` weapons, treat the reach as the larger of 5 or the actual weapon reach.

Specifically:

```python
    @property
    def base_cost(self):
        my_reach = self.reach
        mult = 1.0
        for aa in self.attributes:
            mult += aa.COST_MODIFIER - 1.0
            if hasattr(aa, 'MIN_REACH_FOR_COSTING`):
                my_reach = max(my_reach, aa.MIN_REACH_FOR_COSTING)
        return int(
            (self.COST_FACTOR * (self.damage ** 2) *
            (self.accuracy ** 2 // 10 + self.accuracy + 1) *
            (self.penetration ** 2 // 5 + self.penetration + 1) *
            ((my_reach ** 2 - my_reach) // 2 + 1)) * mult
        )

class ChargeAttack(Singleton):
    # blah
    MIN_REACH_FOR_COSTING = 5
```

Lemme go check the costing with this modification.

**Comment by AmkG** [comment]
So I started thinking more about `reach`.

Some observations:

* In practice, a long-ranged weapon is not so useful because the longer the distance, the more likely that cover will affect you, and the sheer distance is just bad for accuracy.
* However a mid-ranged weapon is definitely an improvement over a short-ranged, non-charge-melee weapon.

The changeover point seems to be about reach 5 or so: I definitely would pick a reach 5 weapon vs a reach 3 or 4, but reach 8 weapons like PHS-8 and Heavy Gauss Rifle are on my mecha for their penetration and damage (respectively) plus the Aim action, not so much for the raw reach (because at long ranges your aim is going to be bad anyway).

If there were a hypothetical 3/3/0 `ChargeAttack` `EnergyWeapon`, I would value it similarly to the LAS-10 (a 3/3/0 `Accurate` `BeamWeapon`), somewhat lower because LAS-10 has the Aim action and is less terrain-dependent.

It seems to me that reach is effectively capped by the accuracy of the weapon.

**Comment by jwvhewitt** [comment]
Maybe I should try collecting some data on this? I've been thinking about recording hit/miss totals to make sure the calculated chance to hit is in the same ballpark as the actual chance of hitting. I could also record damage done by weapon types. I'm not sure how to organize or analyze that data, though.

In order to damage an enemy mecha, your hit roll must beat both its Mobility and Armor defenses. A weapon's Accuracy counteracts Mobility, while Penetration counteracts Armor. If your attack doesn't get past the target's Mobility it misses. If it gets past Mobility but not Armor it lands a non-damaging hit (this can also happen if you do bypass the Armor defense but all the damage gets assigned to an Armor gear). You can't usually beat Armor but not Mobility, except in the case of area of effect weapons. Scatter and area of effect weapons that don't quite beat Mobility might still hit at reduced damage (the Horseshoes and Hand Grenades rule). Energy melee weapons that don't quite beat Armor might still cause reduced damage as well (the Hot Knife Through Butter rule). In the tests I ran before, the best overall weapons split their value between Accuracy and Penetration but better damage can be achieved if you use high-Accuracy weapons against high-Mobility meks and high-Penetration weapons against high-Armor meks.

**Comment by AmkG** [comment]
If possible, please.

>the best overall weapons split their value between Accuracy and Penetration but better damage can be achieved if you use high-Accuracy weapons against high-Mobility meks and high-Penetration weapons against high-Armor meks.

That seems to correlate with my experience: use a Charge weapon (which tend to be high-penetration low-accuracy) with a high-accuracy backup melee weapon (usually Beam Scourge) for high-mobility mechs like Chameleons.  I guess I should try to find the humble Mecha Sword and see how well that works as a backup, since it has pretty good accuracy and combines that with good damage as well.
