### ISSUE TITLE
Should mounts and hands do more?

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#57]
In previous GearHeads, mount points and hands were precious, because items held in mount points had a higher weight limit than items installed directly in the hull (worse, a single mount point could hold a weapon *and* a movement system).  That weight limit went even higher the higher the engine level of your mecha, so they were all the more precious on the Savin.

In GearHead Caramel, I find myself removing all the mount points and hands and just installing weapons directly on arms and turrets.  For melee mecha, melee weapons are generally quite small (Ion Lance only gets 8 slots because of the Haywire attribute, but even a Giant Drill is just 4 slots), and you can usually fit a melee weapon plus reasonable Armor 6 or 7 on a standard size-5 Arm.  For ranged weapons, nabbing an Armor 2 from some cockpit and putting in a size 8 weapon is usually doable; if you specialize mechs, a charging mecha can attract the attention of opponents away from the less-armored ranged mecha, so that is a reasonable design decision.  It all boils down to hands and mounts not doing enough for the design to justify their 0.5 ton weight.

Maybe mounts and hands can add +5 accuracy?

**Comment by AmkG** [comment]
So I'm thinking of two options:

* [ ] Mounts and Hands give a +5 accuracy bonus, OR
* [ ] Installed weapons get a -5 accuracy bonus, which disappears if it is equipped on a mount point or hand.

The latter option might be better if we assume that current designs should "work as-is", since most of them have the main weapons in a mount point or hand (though check out the Musketeer...).

What do you think?

**Comment by jwvhewitt** [comment]
I'm not convinced they need a bonus, yet. And if they do get a bonus it should affect the hit roll rather than Accuracy.

**Comment by AmkG** [comment]
Okay.
