### ISSUE TITLE
"No available audio device" is a crashing error

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#7]
For some reason my laptop audio system is not always working 100%, which is fine by me since I don't really like game sounds very much anyway and usually have volume control set to 0.

When my audio system is acting up, gearhead-caramel completely refuses to start up and just crashes.

I think it would be nicer if this was a "soft" warning error; make it pop up a warning that it cannot find an audio device.  It would be different if it were a "No available video device", but I am not really interested in sounds myself.

**Comment by jwvhewitt** [comment]
Could you tell me the exception it crashes with so I can catch it? I have added a config troubleshooting option to disable audio entirely, but catching the exception would be better.

**Comment by AmkG** [comment]
Unfortunately I didn't save it, but I'll try next time it triggers.

**Comment by jwvhewitt** [comment]
I searched, and assuming your error is the same error other people have gotten, it's probably a pygame.error. A check has been added so that failure to load pygame.mixer will not crash the game.
