### ISSUE TITLE
Change "-15: Range" to more specific "-15: Too Near" or "-15: Too Far"

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#8]
It's mildly confusing to see "-15: Range" in the to-hit modifiers when my mech is standing right next to the target.  Eventually I realized it was because I was using a Particle Cannon at point-blank range, and the modifier disappears when selecting an actual melee weapon, but specifying "Too Near" or "Too Far" would probably have helped better than mere "Range", which by default I would interpret as "Too Far".

**Comment by AmkG** [comment]
Specifying that the modifier comes from the selected weapon would probably also be good --- i.e. Too Near For Weapon, or Too Far For Weapon

**Comment by jwvhewitt** [comment]
Done.
