### ISSUE TITLE
Room prop still blocking door

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#84]
![Screenshot from 2020-05-04 12-19-03](https://user-images.githubusercontent.com/3140/80935952-a0ac9d80-8e01-11ea-8d81-460bd1565cf5.png)

Looks like #42 isn't completely resolved?

**Comment by jwvhewitt** [comment]
I think I know what's wrong- I assumed doors would generate with a waypoint on the same tile (the part which handles the open/close mechanism), but sometimes doors are generated as open doors with no waypoint. So now it will not place decor on any tile which subclasses DoorTerrain.
