### ISSUE TITLE
Request: Friend-or-foe identification

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#9]
I once confusedly killed my own lancemate, because zey had the bad luck of being colored similarly to the current enemy.

It would be nice if the targeting system had a simple friend/foe identification, such as using blue color on the tile hover when targeting them, or a simple "friend"/"foe" keyword somewhere.

Even today's fighting platforms have some kind of [IFF](https://en.wikipedia.org/wiki/Identification_friend_or_foe) already, it seems plausible that such things would still exist in a future with 18-meter rogue mechs.

**Comment by AmkG** [comment]
Current workaround is for me to memorize the names of all my lancemates, and any rescue target, but that's a bit of a load on memory.

**Comment by jwvhewitt** [comment]
![GHC_HostileUnit](https://user-images.githubusercontent.com/1691593/79642607-8f487c00-81d9-11ea-9275-386907128f6e.png)
Thought for a while about how to represent this graphically; in the end I just dropped a big "HOSTILE UNIT" in the middle of the status display.

It would also be good if there were an "Are you sure?" prompt when firing on friendly units or empty tiles (with non-area of effect weapons).

**Comment by AmkG** [comment]
Looks OK.
