### ISSUE TITLE
Randomly-generated chars should get cyberware

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#94]
If cyberware is so awesome, randoms will get a few, right?  Right??  Right.  So something in the chargen?

`_CyberwareInstaller` class in `game.cyberdoc` can assist in installing cyberware in randoms while ensuring that violations do not occur.  It can be provided an `alert` function which when called means installation failed, a `choose` function that should return an index to the given list except for the last (because the last is always "Cancel"), and a `CyberwareSource`, which could be `AllCyberwareSource` or some variant.

**Comment by jwvhewitt** [comment]
This is a good idea. Some of the current jobs should probably be given the Cybertech skill (Silver Knight, Gladiator) and there could be a small random chance (similar to the mutation chance) for other NPCs to get cybered. Also: the presence of the Cybertech skill should be passed to the portrait generator so cybered characters can get cybered portraits. Which probably won't match their actual implants but what odds.

**Comment by AmkG** [comment]
> Also: the presence of the Cybertech skill should be passed to the portrait generator so cybered characters can get cybered portraits.

If portrait generation is done after installing cyberware, the exact location and module it is on can be passed as well, though of course actually making all the graphics for the possible locations would be awfully difficult.

**Comment by AmkG** [comment]
Should I hook this into `gears.selector.random_character`?

**Comment by AmkG** [comment]
It looks like mutation is a possibility for lancemates only, not random chars?

So here's my proposal:

* `random_pilot` looks very similar to `random_ character`, so I think it should just call `random_character` with `job = selector.ALL_JOBS["Mecha Pilot"]` and maybe some other args.
* Add a `can_cyberize` argument to `random_character`.  If unspecified, default to `False` if named character, `True` otherwise (can use `can_cyberize = None` in arglist: `not None is False`).
* After the `base.Character` constructor, if `can_cyberize`, roll a six-sided die and if it comes up 1, try to install cyberware!
* If we try to install cyberware, do this 1 + `char.get_stat(stats.Cybertech)` times:
   * Select a random cyberware.
   * Install cyberware via `game.cyberdoc._CyberwareInstaller` (probably should move that class, and `CyberwareSource`, to a module in `gears/` instead).
   * If it fails, ignore.  If we need to select a location to install, take a random location.

Is that fine? It means random NPCs get cyberware.  Random enemies can get cyberware.  Even random lancemates can get cyberware.  Is that good?
